// src/client/svelte/CompanionTrace.svelte
<script lang="ts">
  import { X } from "lucide-svelte";
  import { fetchMcpTrace, type McpClientInfo, type McpTraceEvent, type McpTraceKind } from "../lib/api";

  type Props = {
    open: boolean;
    clients: McpClientInfo[];
    onClose: () => void;
    onFocusTarget?: (target: unknown) => void;
  };

  let { open, clients, onClose, onFocusTarget }: Props = $props();

  const POLL_INTERVAL_MS = 4_000;
  const DEFAULT_LIMIT = 50;

  const KIND_LABELS: Record<McpTraceKind, string> = {
    read: "read",
    write: "write",
    comment: "comment",
    export: "export",
    "proposal-created": "proposed",
    "proposal-accepted": "accepted",
    "proposal-rejected": "rejected",
    error: "error"
  };

  function relativeTime(at: number): string {
    const deltaS = Math.floor((Date.now() - at) / 1000);
    if (deltaS < 5) return "just now";
    if (deltaS < 60) return `${deltaS}s ago`;
    const deltaM = Math.floor(deltaS / 60);
    if (deltaM < 60) return `${deltaM}m ago`;
    const deltaH = Math.floor(deltaM / 60);
    return `${deltaH}h ago`;
  }

  function isSpatialTarget(target: unknown): boolean {
    if (!target || typeof target !== "object") return false;
    const t = target as { kind?: unknown };
    return typeof t.kind === "string" && t.kind !== "canvas";
  }

  let activeClientId = $state<string | null>(null);
  let events = $state<McpTraceEvent[]>([]);
  let fetchError = $state<string | null>(null);

  const targetClientId = $derived(activeClientId ?? clients[0]?.clientId ?? null);
  const activeClient = $derived(clients.find((c) => c.clientId === targetClientId) ?? clients[0] ?? null);

  async function fetchTrace(clientId: string): Promise<void> {
    try {
      const result = await fetchMcpTrace(clientId, DEFAULT_LIMIT);
      events = result.trace;
      fetchError = null;
    } catch (err) {
      fetchError = err instanceof Error ? err.message : "Trace fetch failed";
    }
  }

  // Poll the active client's trace while open, mirroring CompanionTrace.tsx.
  $effect(() => {
    const clientId = targetClientId;
    if (!open || !clientId) {
      events = [];
      return;
    }
    void fetchTrace(clientId);
    const id = window.setInterval(() => {
      void fetchTrace(clientId);
    }, POLL_INTERVAL_MS);
    return () => window.clearInterval(id);
  });
</script>

{#if open}
  <aside
    id="companion-trace"
    class="companion-trace-drawer"
    aria-label="Agent activity trail"
    onpointerdown={(event) => event.stopPropagation()}
    oncontextmenu={(event) => event.preventDefault()}
  >
    <div class="companion-trace-head">
      <div>
        <span>Agent Trace</span>
        <strong>{activeClient?.label ?? "No client"}</strong>
      </div>
      <button class="icon-button" type="button" onclick={onClose} aria-label="Close agent trace" title="Close agent trace">
        <X size={15} />
      </button>
    </div>

    {#if clients.length > 1}
      <div class="companion-trace-filter" role="list" aria-label="Filter by client">
        {#each clients as client (client.clientId)}
          <!-- svelte-ignore a11y_no_interactive_element_to_noninteractive_role -->
          <!-- svelte-ignore a11y_role_supports_aria_props -->
          <button
            type="button"
            role="listitem"
            class="companion-trace-chip {client.clientId === targetClientId ? 'is-active' : ''}"
            style:--chip-color={client.color}
            onclick={() => (activeClientId = client.clientId)}
            title={`${client.label} v${client.version}`}
            aria-pressed={client.clientId === targetClientId}
          >
            <span class="companion-trace-chip-icon" style:background={client.color}>
              {(client.label[0] ?? "?").toUpperCase()}
            </span>
            <span class="companion-trace-chip-label">{client.label}</span>
          </button>
        {/each}
      </div>
    {/if}

    {#if fetchError}
      <div class="companion-trace-error" role="alert">{fetchError}</div>
    {:else if events.length === 0}
      <div class="companion-trace-empty">No activity yet</div>
    {:else}
      <ol class="companion-trace-list" aria-label="Recent operations">
        {#each events as event, index (event.operationId ?? `read-${index}-${event.at}`)}
          {@const kindLabel = KIND_LABELS[event.kind] ?? event.kind}
          {@const isError = event.kind === "error"}
          {@const isPending = event.kind === "proposal-created"}
          {@const clickable = onFocusTarget !== undefined && isSpatialTarget(event.target)}
          {@const clientColor = activeClient?.color ?? "#888"}
          <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
          <li
            class="companion-trace-row {isError ? 'is-error' : ''} {isPending ? 'is-pending' : ''} {clickable ? 'companion-trace-row-focusable' : ''}"
            role={clickable ? "button" : "listitem"}
            tabindex={clickable ? 0 : undefined}
            title={clickable ? "Focus on canvas" : undefined}
            onclick={clickable ? () => onFocusTarget?.(event.target) : undefined}
            onkeydown={clickable
              ? (e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    onFocusTarget?.(event.target);
                  }
                }
              : undefined}
          >
            <span class="companion-trace-kind-dot" style:background={isError ? "var(--bad)" : clientColor} aria-hidden="true"></span>
            <div class="companion-trace-content">
              <span class="companion-trace-kind">{kindLabel}</span>
              <span class="companion-trace-summary">{event.summary}</span>
              {#if event.errorMessage}
                <span class="companion-trace-error-msg">{event.errorMessage}</span>
              {/if}
            </div>
            <time
              class="companion-trace-time"
              datetime={new Date(event.at).toISOString()}
              title={new Date(event.at).toLocaleString()}
            >
              {relativeTime(event.at)}
            </time>
          </li>
        {/each}
      </ol>
    {/if}
  </aside>
{/if}

// src/client/components/CompanionTrace.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { X } from "lucide-react";
import { fetchMcpTrace, type McpClientInfo, type McpTraceEvent, type McpTraceKind } from "../lib/api";

type CompanionTraceProps = {
  open: boolean;
  clients: McpClientInfo[];
  onClose: () => void;
  onFocusTarget?: (target: unknown) => void;
};

const POLL_INTERVAL_MS = 4_000;
const DEFAULT_LIMIT = 50;

const KIND_LABELS: Record<McpTraceKind, string> = {
  read: "read",
  write: "write",
  comment: "comment",
  export: "export",
  "proposal-created": "proposed",
  "proposal-accepted": "accepted",
  "proposal-rejected": "rejected",
  error: "error"
};

function relativeTime(at: number): string {
  const deltaS = Math.floor((Date.now() - at) / 1000);
  if (deltaS < 5) return "just now";
  if (deltaS < 60) return `${deltaS}s ago`;
  const deltaM = Math.floor(deltaS / 60);
  if (deltaM < 60) return `${deltaM}m ago`;
  const deltaH = Math.floor(deltaM / 60);
  return `${deltaH}h ago`;
}

export function CompanionTrace({ open, clients, onClose, onFocusTarget }: CompanionTraceProps) {
  const [activeClientId, setActiveClientId] = useState<string | null>(null);
  const [events, setEvents] = useState<McpTraceEvent[]>([]);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const pollRef = useRef<number | null>(null);

  const targetClientId = activeClientId ?? clients[0]?.clientId ?? null;

  const fetchTrace = useCallback(async (clientId: string) => {
    try {
      const result = await fetchMcpTrace(clientId, DEFAULT_LIMIT);
      setEvents(result.trace);
      setFetchError(null);
    } catch (err) {
      setFetchError(err instanceof Error ? err.message : "Trace fetch failed");
    }
  }, []);

  useEffect(() => {
    if (!open || !targetClientId) {
      setEvents([]);
      return;
    }

    void fetchTrace(targetClientId);

    pollRef.current = window.setInterval(() => {
      void fetchTrace(targetClientId);
    }, POLL_INTERVAL_MS);

    return () => {
      if (pollRef.current !== null) window.clearInterval(pollRef.current);
      pollRef.current = null;
    };
  }, [open, targetClientId, fetchTrace]);

  if (!open) return null;

  const activeClient = clients.find((c) => c.clientId === targetClientId) ?? clients[0] ?? null;

  return (
    <aside
      id="companion-trace"
      className="companion-trace-drawer"
      aria-label="Agent activity trail"
      onPointerDown={(event) => event.stopPropagation()}
      onContextMenu={(event) => event.preventDefault()}
    >
      <div className="companion-trace-head">
        <div>
          <span>Agent Trace</span>
          <strong>{activeClient?.label ?? "No client"}</strong>
        </div>
        <button className="icon-button" type="button" onClick={onClose} aria-label="Close agent trace" title="Close agent trace">
          <X size={15} />
        </button>
      </div>

      {clients.length > 1 && (
        <div className="companion-trace-filter" role="list" aria-label="Filter by client">
          {clients.map((client) => (
            <button
              key={client.clientId}
              type="button"
              role="listitem"
              className={`companion-trace-chip ${client.clientId === targetClientId ? "is-active" : ""}`}
              style={{ "--chip-color": client.color } as React.CSSProperties}
              onClick={() => setActiveClientId(client.clientId)}
              title={`${client.label} v${client.version}`}
              aria-pressed={client.clientId === targetClientId}
            >
              <span
                className="companion-trace-chip-icon"
                style={{ background: client.color }}
              >
                {(client.label[0] ?? "?").toUpperCase()}
              </span>
              <span className="companion-trace-chip-label">{client.label}</span>
            </button>
          ))}
        </div>
      )}

      {fetchError ? (
        <div className="companion-trace-error" role="alert">{fetchError}</div>
      ) : events.length === 0 ? (
        <div className="companion-trace-empty">No activity yet</div>
      ) : (
        <ol className="companion-trace-list" aria-label="Recent operations">
          {events.map((event, index) => (
            <TraceRow
              key={event.operationId ?? `read-${index}-${event.at}`}
              event={event}
              clientColor={activeClient?.color ?? "#888"}
              onFocusTarget={onFocusTarget}
            />
          ))}
        </ol>
      )}
    </aside>
  );
}

type TraceRowProps = {
  event: McpTraceEvent;
  clientColor: string;
  onFocusTarget?: (target: unknown) => void;
};

function isSpatialTarget(target: unknown): boolean {
  if (!target || typeof target !== "object") return false;
  const t = target as { kind?: unknown };
  return typeof t.kind === "string" && t.kind !== "canvas";
}

function TraceRow({ event, clientColor, onFocusTarget }: TraceRowProps) {
  const kindLabel = KIND_LABELS[event.kind] ?? event.kind;
  const isError = event.kind === "error";
  const isPending = event.kind === "proposal-created";
  const clickable = onFocusTarget !== undefined && isSpatialTarget(event.target);

  return (
    <li
      className={`companion-trace-row ${isError ? "is-error" : ""} ${isPending ? "is-pending" : ""} ${clickable ? "companion-trace-row-focusable" : ""}`}
      role={clickable ? "button" : "listitem"}
      tabIndex={clickable ? 0 : undefined}
      title={clickable ? "Focus on canvas" : undefined}
      onClick={clickable ? () => onFocusTarget(event.target) : undefined}
      onKeyDown={clickable ? (e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onFocusTarget(event.target); } } : undefined}
    >
      <span
        className="companion-trace-kind-dot"
        style={{ background: isError ? "var(--bad)" : clientColor }}
        aria-hidden="true"
      />
      <div className="companion-trace-content">
        <span className="companion-trace-kind">{kindLabel}</span>
        <span className="companion-trace-summary">{event.summary}</span>
        {event.errorMessage && (
          <span className="companion-trace-error-msg">{event.errorMessage}</span>
        )}
      </div>
      <time className="companion-trace-time" dateTime={new Date(event.at).toISOString()} title={new Date(event.at).toLocaleString()}>
        {relativeTime(event.at)}
      </time>
    </li>
  );
}
