// src/client/svelte/RendererDiagnosticsDrawer.svelte
<script lang="ts">
  import { X } from "lucide-svelte";
  import type { CameraState } from "../../shared/renderScene";
  import type { SceneSelection } from "../../shared/schema";
  import type { RendererHealth, RendererStats } from "../lib/canvasHost";

  type Props = {
    open: boolean;
    stats: RendererStats | null;
    health: RendererHealth | null;
    camera: CameraState;
    selection: SceneSelection;
    selectedTargetLabel: string;
    status: string;
    rendererStatus: string;
    onClose: () => void;
  };

  let { open, stats, health, camera, selection, selectedTargetLabel, status, rendererStatus, onClose }: Props = $props();

  function ms(value: number): string {
    return `${value.toFixed(2)} ms`;
  }

  function bytes(value: number): string {
    return `${Math.round(value / 1024 / 1024)} MB`;
  }

  function yesNo(value: boolean): string {
    return value ? "yes" : "no";
  }

  function numberValue(value: number | null | undefined): string | null {
    return value === null || value === undefined ? null : String(value);
  }

  function cachePair(hits: number | null | undefined, misses: number | null | undefined): string | null {
    if (hits === null || hits === undefined) return null;
    return `${hits} hit / ${misses ?? 0} miss`;
  }

  function slotValue(slots: number | null | undefined, freeSlots: number | null | undefined): string | null {
    if (slots === null || slots === undefined) return null;
    const free = freeSlots ?? 0;
    return `${slots - free} used / ${free} free / ${slots} total`;
  }

  function rustCameraValue(s: RendererStats | null): string | null {
    if (!s || s.rustCameraX === null || s.rustCameraY === null || s.rustCameraZoom === null) return null;
    return `${s.rustCameraZoom.toFixed(3)}x @ ${Math.round(s.rustCameraX)}, ${Math.round(s.rustCameraY)}`;
  }

  function rustLastHitValue(s: RendererStats | null): string | null {
    if (!s?.rustLastHitKind) return null;
    const target = s.rustLastHitId ? `${s.rustLastHitKind}:${s.rustLastHitId}` : s.rustLastHitKind;
    const field = s.rustLastHitField ? `:${s.rustLastHitField}` : "";
    const port = s.rustLastHitPort ? `:${s.rustLastHitPort}` : "";
    const screen =
      s.rustLastHitScreenX === null || s.rustLastHitScreenY === null
        ? ""
        : ` @ ${Math.round(s.rustLastHitScreenX)}, ${Math.round(s.rustLastHitScreenY)}`;
    return `${target}${field}${port}${screen}`;
  }

  function selectionValue(sel: SceneSelection): string {
    if (sel.kind === "canvas") return "canvas";
    if (sel.kind === "multi") return `multi:${sel.ids.length} objects`;
    return `${sel.kind}:${sel.id}`;
  }
</script>

{#snippet row(label: string, value: string | null | undefined)}
  <div class="renderer-diagnostics-row">
    <dt>{label}</dt>
    <dd>{value ?? "-"}</dd>
  </div>
{/snippet}

{#if open}
  <aside
    id="renderer-diagnostics"
    class="renderer-diagnostics-drawer"
    aria-label="Renderer diagnostics"
    onpointerdown={(event) => event.stopPropagation()}
    oncontextmenu={(event) => event.preventDefault()}
  >
    <div class="renderer-diagnostics-head">
      <div>
        <span>Diagnostics</span>
        <strong>{stats?.drawBackend ?? "renderer pending"}</strong>
      </div>
      <button class="icon-button" type="button" onclick={onClose} aria-label="Close diagnostics" title="Close diagnostics">
        <X size={15} />
      </button>
    </div>

    <section class="renderer-diagnostics-section">
      <h2>Health</h2>
      <dl>
        {@render row("Backend", stats?.backend)}
        {@render row("Renderer state", health?.state)}
        {@render row("Renderer detail", health?.detail)}
        {@render row("Rust core", health ? yesNo(health.rustAvailable) : null)}
        {@render row("Rust backend", health?.rustBackend)}
        {@render row("Draw backend", stats?.drawBackend)}
        {@render row("WebGPU available", stats ? yesNo(stats.webGpuRendererAvailable) : health ? yesNo(health.webGpuRendererAvailable) : null)}
        {@render row("App status/error", status || "Ready")}
        {@render row("Renderer status/error", rendererStatus || "No renderer status yet")}
      </dl>
    </section>

    <section class="renderer-diagnostics-section">
      <h2>Frame</h2>
      <dl>
        {@render row("Frame", stats ? ms(stats.frameMs) : null)}
        {@render row("Render", stats ? ms(stats.renderMs) : null)}
        {@render row("Visible", stats ? `${stats.visibleGroups} groups / ${stats.visibleCards} cards / ${stats.visibleEdges} edges` : null)}
        {@render row("Total", stats ? `${stats.totalGroups} groups / ${stats.totalCards} cards / ${stats.totalEdges} edges` : null)}
        {@render row("Memory", stats?.memoryBytes === null || stats?.memoryBytes === undefined ? null : bytes(stats.memoryBytes))}
        {@render row("Boundary calls", stats ? String(stats.boundaryCalls) : null)}
        {@render row("Rust boundary calls", stats ? String(stats.rustBoundaryCalls) : null)}
        {@render row("Input batch", stats ? String(stats.inputBatchSize) : null)}
      </dl>
    </section>

    <section class="renderer-diagnostics-section">
      <h2>Glyphs And Cache</h2>
      <dl>
        {@render row("Scene cache", stats ? `${stats.cacheHits} hit / ${stats.cacheMisses} miss` : null)}
        {@render row("Shaped glyphs", numberValue(stats?.rustTextGlyphs))}
        {@render row("Fallback glyphs", numberValue(stats?.rustFallbackGlyphs))}
        {@render row("Fallback runs", numberValue(stats?.rustFontFallbackRuns))}
        {@render row("CJK glyphs", numberValue(stats?.rustCjkGlyphs))}
        {@render row("Missing glyphs", numberValue(stats?.rustMissingGlyphs))}
        {@render row("Atlas glyphs", numberValue(stats?.rustTextAtlasGlyphs))}
        {@render row("Atlas overflow", numberValue(stats?.rustTextAtlasOverflowGlyphs))}
        {@render row("Missing rasters", numberValue(stats?.rustTextMissingRasterGlyphs))}
        {@render row("Raster cache", cachePair(stats?.rustTextRasterCacheHits, stats?.rustTextRasterCacheMisses))}
        {@render row("Layout cache", cachePair(stats?.rustTextLayoutCacheHits, stats?.rustTextLayoutCacheMisses))}
        {@render row("Style tokens", numberValue(stats?.rustStyleTokens))}
      </dl>
    </section>

    <section class="renderer-diagnostics-section">
      <h2>GPU Writes</h2>
      <dl>
        {@render row("Patch updates", numberValue(stats?.rustPatchUpdates))}
        {@render row("Dirty writes", numberValue(stats?.rustDirtyWrites))}
        {@render row("Full rebuilds", numberValue(stats?.rustFullRebuilds))}
        {@render row("GPU vertices", numberValue(stats?.rustGpuVertices))}
        {@render row("Drawn vertices", numberValue(stats?.rustDrawnVertices))}
        {@render row("Draw ranges", numberValue(stats?.rustDrawRanges))}
        {@render row("Vertex truncations", numberValue(stats?.rustVertexTruncations))}
        {@render row("Truncated vertices", numberValue(stats?.rustTruncatedVertices))}
      </dl>
    </section>

    <section class="renderer-diagnostics-section">
      <h2>Buffers</h2>
      <dl>
        {@render row("Group slots", slotValue(stats?.rustGroupSlots, stats?.rustFreeGroupSlots))}
        {@render row("Group grows", numberValue(stats?.rustGroupCapacityGrows))}
        {@render row("Group compactions", numberValue(stats?.rustGroupCompactions))}
        {@render row("Card slots", slotValue(stats?.rustCardSlots, stats?.rustFreeCardSlots))}
        {@render row("Card grows", numberValue(stats?.rustCardCapacityGrows))}
        {@render row("Card compactions", numberValue(stats?.rustCardCompactions))}
        {@render row("Edge slots", slotValue(stats?.rustEdgeSlots, stats?.rustFreeEdgeSlots))}
        {@render row("Edge grows", numberValue(stats?.rustEdgeCapacityGrows))}
        {@render row("Edge compactions", numberValue(stats?.rustEdgeCompactions))}
      </dl>
    </section>

    <section class="renderer-diagnostics-section">
      <h2>Camera And Target</h2>
      <dl>
        {@render row("App camera", `${camera.zoom.toFixed(3)}x @ ${Math.round(camera.x)}, ${Math.round(camera.y)}`)}
        {@render row("Rust camera", rustCameraValue(stats))}
        {@render row("App selection", selectionValue(selection))}
        {@render row("Rust selection", stats?.rustSelectionKind ? selectionValue({ kind: stats.rustSelectionKind, id: stats.rustSelectionId ?? undefined } as SceneSelection) : null)}
        {@render row("Rust last hit", rustLastHitValue(stats))}
        {@render row("Selected target", selectedTargetLabel)}
      </dl>
    </section>
  </aside>
{/if}

// src/client/components/RendererDiagnosticsDrawer.tsx
import { X } from "lucide-react";
import type { ReactNode } from "react";
import type { CameraState } from "../../shared/renderScene";
import type { SceneSelection } from "../../shared/schema";
import type { RendererHealth, RendererStats } from "./RendererCanvasHost";

type RendererDiagnosticsDrawerProps = {
  open: boolean;
  stats: RendererStats | null;
  health: RendererHealth | null;
  camera: CameraState;
  selection: SceneSelection;
  selectedTargetLabel: string;
  status: string;
  rendererStatus: string;
  onClose: () => void;
};

export function RendererDiagnosticsDrawer({
  open,
  stats,
  health,
  camera,
  selection,
  selectedTargetLabel,
  status,
  rendererStatus,
  onClose
}: RendererDiagnosticsDrawerProps) {
  if (!open) return null;

  return (
    <aside
      id="renderer-diagnostics"
      className="renderer-diagnostics-drawer"
      aria-label="Renderer diagnostics"
      onPointerDown={(event) => event.stopPropagation()}
      onContextMenu={(event) => event.preventDefault()}
    >
      <div className="renderer-diagnostics-head">
        <div>
          <span>Diagnostics</span>
          <strong>{stats?.drawBackend ?? "renderer pending"}</strong>
        </div>
        <button className="icon-button" type="button" onClick={onClose} aria-label="Close diagnostics" title="Close diagnostics">
          <X size={15} />
        </button>
      </div>

      <DiagnosticsSection title="Health">
        <DiagnosticRow label="Backend" value={stats?.backend} />
        <DiagnosticRow label="Renderer state" value={health?.state} />
        <DiagnosticRow label="Renderer detail" value={health?.detail} />
        <DiagnosticRow label="Rust core" value={health ? yesNo(health.rustAvailable) : null} />
        <DiagnosticRow label="Rust backend" value={health?.rustBackend} />
        <DiagnosticRow label="Draw backend" value={stats?.drawBackend} />
        <DiagnosticRow label="WebGPU available" value={stats ? yesNo(stats.webGpuRendererAvailable) : health ? yesNo(health.webGpuRendererAvailable) : null} />
        <DiagnosticRow label="App status/error" value={status || "Ready"} />
        <DiagnosticRow label="Renderer status/error" value={rendererStatus || "No renderer status yet"} />
      </DiagnosticsSection>

      <DiagnosticsSection title="Frame">
        <DiagnosticRow label="Frame" value={stats ? ms(stats.frameMs) : null} />
        <DiagnosticRow label="Render" value={stats ? ms(stats.renderMs) : null} />
        <DiagnosticRow label="Visible" value={stats ? `${stats.visibleGroups} groups / ${stats.visibleCards} cards / ${stats.visibleEdges} edges` : null} />
        <DiagnosticRow label="Total" value={stats ? `${stats.totalGroups} groups / ${stats.totalCards} cards / ${stats.totalEdges} edges` : null} />
        <DiagnosticRow label="Memory" value={stats?.memoryBytes === null || stats?.memoryBytes === undefined ? null : bytes(stats.memoryBytes)} />
        <DiagnosticRow label="Boundary calls" value={stats ? String(stats.boundaryCalls) : null} />
        <DiagnosticRow label="Rust boundary calls" value={stats ? String(stats.rustBoundaryCalls) : null} />
        <DiagnosticRow label="Input batch" value={stats ? String(stats.inputBatchSize) : null} />
      </DiagnosticsSection>

      <DiagnosticsSection title="Glyphs And Cache">
        <DiagnosticRow label="Scene cache" value={stats ? `${stats.cacheHits} hit / ${stats.cacheMisses} miss` : null} />
        <DiagnosticRow label="Shaped glyphs" value={numberValue(stats?.rustTextGlyphs)} />
        <DiagnosticRow label="Fallback glyphs" value={numberValue(stats?.rustFallbackGlyphs)} />
        <DiagnosticRow label="Fallback runs" value={numberValue(stats?.rustFontFallbackRuns)} />
        <DiagnosticRow label="CJK glyphs" value={numberValue(stats?.rustCjkGlyphs)} />
        <DiagnosticRow label="Missing glyphs" value={numberValue(stats?.rustMissingGlyphs)} />
        <DiagnosticRow label="Atlas glyphs" value={numberValue(stats?.rustTextAtlasGlyphs)} />
        <DiagnosticRow label="Atlas overflow" value={numberValue(stats?.rustTextAtlasOverflowGlyphs)} />
        <DiagnosticRow label="Missing rasters" value={numberValue(stats?.rustTextMissingRasterGlyphs)} />
        <DiagnosticRow label="Raster cache" value={cachePair(stats?.rustTextRasterCacheHits, stats?.rustTextRasterCacheMisses)} />
        <DiagnosticRow label="Layout cache" value={cachePair(stats?.rustTextLayoutCacheHits, stats?.rustTextLayoutCacheMisses)} />
        <DiagnosticRow label="Style tokens" value={numberValue(stats?.rustStyleTokens)} />
      </DiagnosticsSection>

      <DiagnosticsSection title="GPU Writes">
        <DiagnosticRow label="Patch updates" value={numberValue(stats?.rustPatchUpdates)} />
        <DiagnosticRow label="Dirty writes" value={numberValue(stats?.rustDirtyWrites)} />
        <DiagnosticRow label="Full rebuilds" value={numberValue(stats?.rustFullRebuilds)} />
        <DiagnosticRow label="GPU vertices" value={numberValue(stats?.rustGpuVertices)} />
        <DiagnosticRow label="Drawn vertices" value={numberValue(stats?.rustDrawnVertices)} />
        <DiagnosticRow label="Draw ranges" value={numberValue(stats?.rustDrawRanges)} />
        <DiagnosticRow label="Vertex truncations" value={numberValue(stats?.rustVertexTruncations)} />
        <DiagnosticRow label="Truncated vertices" value={numberValue(stats?.rustTruncatedVertices)} />
      </DiagnosticsSection>

      <DiagnosticsSection title="Buffers">
        <DiagnosticRow label="Group slots" value={slotValue(stats?.rustGroupSlots, stats?.rustFreeGroupSlots)} />
        <DiagnosticRow label="Group grows" value={numberValue(stats?.rustGroupCapacityGrows)} />
        <DiagnosticRow label="Group compactions" value={numberValue(stats?.rustGroupCompactions)} />
        <DiagnosticRow label="Card slots" value={slotValue(stats?.rustCardSlots, stats?.rustFreeCardSlots)} />
        <DiagnosticRow label="Card grows" value={numberValue(stats?.rustCardCapacityGrows)} />
        <DiagnosticRow label="Card compactions" value={numberValue(stats?.rustCardCompactions)} />
        <DiagnosticRow label="Edge slots" value={slotValue(stats?.rustEdgeSlots, stats?.rustFreeEdgeSlots)} />
        <DiagnosticRow label="Edge grows" value={numberValue(stats?.rustEdgeCapacityGrows)} />
        <DiagnosticRow label="Edge compactions" value={numberValue(stats?.rustEdgeCompactions)} />
      </DiagnosticsSection>

      <DiagnosticsSection title="Camera And Target">
        <DiagnosticRow label="App camera" value={`${camera.zoom.toFixed(3)}x @ ${Math.round(camera.x)}, ${Math.round(camera.y)}`} />
        <DiagnosticRow label="Rust camera" value={rustCameraValue(stats)} />
        <DiagnosticRow label="App selection" value={selectionValue(selection)} />
        <DiagnosticRow label="Rust selection" value={stats?.rustSelectionKind ? selectionValue({ kind: stats.rustSelectionKind, id: stats.rustSelectionId ?? undefined } as SceneSelection) : null} />
        <DiagnosticRow label="Rust last hit" value={rustLastHitValue(stats)} />
        <DiagnosticRow label="Selected target" value={selectedTargetLabel} />
      </DiagnosticsSection>
    </aside>
  );
}

function DiagnosticsSection({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="renderer-diagnostics-section">
      <h2>{title}</h2>
      <dl>{children}</dl>
    </section>
  );
}

function DiagnosticRow({ label, value }: { label: string; value: string | null | undefined }) {
  return (
    <div className="renderer-diagnostics-row">
      <dt>{label}</dt>
      <dd>{value ?? "-"}</dd>
    </div>
  );
}

function ms(value: number): string {
  return `${value.toFixed(2)} ms`;
}

function bytes(value: number): string {
  return `${Math.round(value / 1024 / 1024)} MB`;
}

function yesNo(value: boolean): string {
  return value ? "yes" : "no";
}

function numberValue(value: number | null | undefined): string | null {
  return value === null || value === undefined ? null : String(value);
}

function cachePair(hits: number | null | undefined, misses: number | null | undefined): string | null {
  if (hits === null || hits === undefined) return null;
  return `${hits} hit / ${misses ?? 0} miss`;
}

function slotValue(slots: number | null | undefined, freeSlots: number | null | undefined): string | null {
  if (slots === null || slots === undefined) return null;
  const free = freeSlots ?? 0;
  return `${slots - free} used / ${free} free / ${slots} total`;
}

function rustCameraValue(stats: RendererStats | null): string | null {
  if (!stats || stats.rustCameraX === null || stats.rustCameraY === null || stats.rustCameraZoom === null) return null;
  return `${stats.rustCameraZoom.toFixed(3)}x @ ${Math.round(stats.rustCameraX)}, ${Math.round(stats.rustCameraY)}`;
}

function rustLastHitValue(stats: RendererStats | null): string | null {
  if (!stats?.rustLastHitKind) return null;
  const target = stats.rustLastHitId ? `${stats.rustLastHitKind}:${stats.rustLastHitId}` : stats.rustLastHitKind;
  const field = stats.rustLastHitField ? `:${stats.rustLastHitField}` : "";
  const port = stats.rustLastHitPort ? `:${stats.rustLastHitPort}` : "";
  const screen =
    stats.rustLastHitScreenX === null || stats.rustLastHitScreenY === null
      ? ""
      : ` @ ${Math.round(stats.rustLastHitScreenX)}, ${Math.round(stats.rustLastHitScreenY)}`;
  return `${target}${field}${port}${screen}`;
}

function selectionValue(selection: SceneSelection): string {
  if (selection.kind === "canvas") return "canvas";
  if (selection.kind === "multi") return `multi:${selection.ids.length} objects`;
  return `${selection.kind}:${selection.id}`;
}
